# Generated by Django 4.1 on 2022-08-26 19:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique identifier for this particular book', primary_key=True, serialize=False),
        ),
    ]
